### ISSUE TITLE
User-defined schema description is overriden

### ISSUE THREAD

**Issue by botflux** [GiovanniCardamone/class-schema#3]
Hey, 

According to the `@schema` decorator implementation, the schema description is always overriden.
[line](https://github.com/GiovanniCardamone/class-schema/blob/a001cf2094afdba449acbb721e9dfa12d4892f1a/src/decorators/schema.ts#L17)

I can make an MR to fix this problem.
Have a nice day!

**Comment by GiovanniCardamone** [comment]
Oh yes, i didn't noticed that, you can make a MR and I will merge, thanks for the support!

**Comment by botflux** [comment]
#4

**Comment by GiovanniCardamone** [comment]
released! Thanks a lot
